"""Semantic Memory — stores abstract knowledge patterns with vector retrieval.

Design decisions:
- KnowledgeEntry is the atomic unit: title + content + category + embedding.
- Uses pure-Python cosine similarity (no numpy dependency).
- Embedding is generated by a simple hash-based pseudo-encoder for offline use;
  a real system would swap this for an actual embedding model.
- Supports add / search / delete operations.
"""

from __future__ import annotations

import hashlib
import math
import uuid
from typing import Any

from pydantic import BaseModel, Field


class KnowledgeEntry(BaseModel):
    entry_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:12])
    title: str
    content: str
    category: str = "code_pattern"  # KnowledgeCategory values
    source_task_id: str = ""  # link back to episodic memory
    embedding: list[float] = Field(default_factory=list)
    confidence: float = 1.0  # 0-1, how confident we are in this knowledge
    metadata: dict[str, Any] = Field(default_factory=dict)

    def model_post_init(self, __context: Any) -> None:
        if not self.embedding:
            self.embedding = _pseudo_embed(self.title + " " + self.content)


# ---------------------------------------------------------------------------
# Pseudo-embedding: deterministic hash → fixed-dim vector
# ---------------------------------------------------------------------------

_EMBED_DIM = 64


def _pseudo_embed(text: str, dim: int = _EMBED_DIM) -> list[float]:
    """Generate a deterministic pseudo-embedding from text.

    Uses SHA-256 hash bytes → normalized float vector.
    Not semantically meaningful, but stable and dependency-free.
    A production system would replace this with a real embedding model.
    """
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    # Repeat hash to fill dim values
    raw = []
    for i in range(dim):
        byte_pair = digest[(2 * i) % len(digest) : (2 * i + 2) % len(digest) + 1]
        try:
            raw.append(int(byte_pair, 16))
        except ValueError:
            raw.append(0)
    # normalize to unit vector
    norm = math.sqrt(sum(v * v for v in raw)) or 1.0
    return [v / norm for v in raw]


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a)) or 1.0
    nb = math.sqrt(sum(x * x for x in b)) or 1.0
    return dot / (na * nb)


# ---------------------------------------------------------------------------
# SemanticMemory
# ---------------------------------------------------------------------------


class SemanticMemory(BaseModel):
    """Knowledge store with vector-based retrieval."""

    entries: list[KnowledgeEntry] = Field(default_factory=list)
    max_entries: int = 5000

    # -- write -------------------------------------------------------------

    def add(self, entry: KnowledgeEntry) -> None:
        self.entries.append(entry)
        if len(self.entries) > self.max_entries:
            self.entries = self.entries[-self.max_entries :]

    def remove(self, entry_id: str) -> bool:
        before = len(self.entries)
        self.entries = [e for e in self.entries if e.entry_id != entry_id]
        return len(self.entries) < before

    # -- query -------------------------------------------------------------

    def search(
        self,
        query: str,
        top_k: int = 5,
        category: str | None = None,
        min_confidence: float = 0.0,
    ) -> list[tuple[KnowledgeEntry, float]]:
        """Return (entry, similarity_score) pairs sorted by descending score."""
        q_emb = _pseudo_embed(query)
        candidates = self.entries
        if category is not None:
            candidates = [e for e in candidates if e.category == category]
        if min_confidence > 0:
            candidates = [e for e in candidates if e.confidence >= min_confidence]

        scored = [
            (e, _cosine_similarity(q_emb, e.embedding)) for e in candidates
        ]
        scored.sort(key=lambda pair: pair[1], reverse=True)
        return scored[:top_k]

    def get_by_id(self, entry_id: str) -> KnowledgeEntry | None:
        for e in self.entries:
            if e.entry_id == entry_id:
                return e
        return None

    def get_by_category(self, category: str) -> list[KnowledgeEntry]:
        return [e for e in self.entries if e.category == category]

    def summary(self) -> dict[str, Any]:
        by_cat: dict[str, int] = {}
        for e in self.entries:
            by_cat[e.category] = by_cat.get(e.category, 0) + 1
        return {
            "total_entries": len(self.entries),
            "by_category": by_cat,
            "avg_confidence": (
                round(sum(e.confidence for e in self.entries) / len(self.entries), 3)
                if self.entries
                else 0.0
            ),
        }
